IF VARTYPE(_SCREEN.UsuarioInfo) = "O" THEN
	_SCREEN.RemoveObject("UsuarioInfo")
ENDIF
USE IN "Usuario"

IF UPPER(JUSTFNAME(APPLICATION.SERVERNAME)) = "VFP9.EXE" THEN
	SET SYSMENU TO DEFAULT
ELSE
	SET SYSMENU OFF
ENDIF

Login()